일부 경로 수정과 파일을 추가하였습니다.
SanghoonSon/commerce pull request #5
Opened 2022-03-23 03:31 UTC by OseongminO

디렉토리 파일중 dao를 사용하자고 했었는데 SI느낌이 많이 나는거같아
Repository를 살려둬봤는데 의견 부탁드리겠습니다.

2022-03-23 05:40 UTC, SanghoonSon requested changes
리뷰드립니다.

2022-03-23 05:40 UTC, SanghoonSon commented on backend/src/main/kotlin/com/study/commerce/product/service/ProductServiceImpl.kt
> +        val product = productRepository.save(Product(productId, category, subCategory, productName, price))
신규 상품 등록이면, Product Id는 영속화(persist)될때까지 알수 없지 않을까라는 생각이 듭니다~

왜냐하면 엔티티를 보면 Id는 자동 생성 전략을 사용하고 있어서요.

그래서 생성자에 Id를 넣을 수가 없을 것 같아요!

2022-03-23 05:40 UTC, SanghoonSon commented on backend/src/main/kotlin/com/study/commerce/product/repository/ProductRepository.kt
> +    fun findByProductId(productId: Long): Product
Entity Id기준으로 데이터를 조회하는 기능은 JpaRepository에서 제공해줍니다.
(Optional로 Return)
* JpaRepository:findById(:id)

JpaRepository에서 단일건에 대한 CRUD는 어느정도 지원될거에요!

2022-03-24 12:02 UTC, OseongminO commented on backend/src/main/kotlin/com/study/commerce/product/repository/ProductRepository.kt
> +    fun findByProductId(productId: Long): Product
jpa에서 해볼수 있는 여러가지 기능들을 사용해보고자 만들어보았습니다.

2022-03-27 11:46 UTC, AYEONGYEO commented
확인했습니다. 고생하셨습니다 :)

2022-03-27 12:04 UTC, SanghoonSon approved these changes

2022-03-27 12:06 UTC, SanghoonSon commented
수고하셨습니다~

2022-03-27 12:07 UTC, closed without merging